name: psd-retrievals
channels:
  - conda-forge
  - pyviz
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - h5netcdf
  - h5py
  - netCDF4
  - cf_xarray
  - xarrayutils
  - zarr
  - pandas
  - dask
  - matplotlib
  - scipy
  - xlrd
  - ipywidgets
  - seaborn
  - scikit-learn
  - xhistogram
  - imbalanced-learn
  - s3fs
  - hvplot
  - opencv
  - pip
  - pip:
      - tensorflow
      - sphinx-pythia-theme
      - pydata-sphinx-theme
      - git+https://github.com/pydata/xarray.git
