name: psd-retrievals
channels:
  - conda-forge
  - pyviz
dependencies:
  - python>=3.9
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - h5netcdf
  - h5py
  - netCDF4
  - xarray
  - cf_xarray
  - xarray-datatree>=0.0.10
  - xarrayutils
  - zarr
  - pandas
  - dask
  - matplotlib
  - scipy
  - xlrd
  - ipywidgets
  - seaborn
  - scikit-learn
  - xhistogram
  - imbalanced-learn
  - pip
  - pip:
      - tensorflow
      - sphinx-pythia-theme
      - pydata-sphinx-theme
